import { DashboardTile, Category } from '../types';

export const categories: Category[] = [
  { id: 'payment-integrity', name: 'Payment Integrity', color: '#F97316' },
  { id: 'claims-management', name: 'Claims Management', color: '#10B981' },
  { id: 'clinical-quality', name: 'Clinical Management', color: '#3B82F6' },
  { id: 'finance-cost', name: 'Cost of Care', color: '#8B5CF6' },
  { id: 'healthcare-economics', name: 'Healthcare Economics', color: '#F59E0B' },
  { id: 'utilization-management', name: 'Utilization Management', color: '#EF4444' },
  { id: 'provider-experience', name: 'Provider Experience', color: '#6B7280' },
  { id: 'member-experience', name: 'Member Experience', color: '#EC4899' },
  { id: 'digital-engagement', name: 'Digital Engagement', color: '#14B8A6' },
  { id: 'call-center-provider', name: 'Call Center - Provider', color: '#F97316' },
  { id: 'call-center-member', name: 'Call Center - Member', color: '#10B981' },
  { id: 'network-contracting', name: 'Network & Contracting', color: '#3B82F6' },
  { id: 'pharmacy', name: 'Pharmacy', color: '#8B5CF6' },
  { id: 'risk-adjustment', name: 'Risk Adjustment', color: '#F59E0B' },
  { id: 'fraud-waste-abuse', name: 'Fraud, Waste, Abuse', color: '#EF4444' },
  { id: 'compliance-regulatory', name: 'Compliance & Regulatory', color: '#6B7280' },
  { id: 'data-quality', name: 'Data Quality & Platform', color: '#EC4899' },
  { id: 'hr-workforce', name: 'HR/Workforce', color: '#14B8A6' },
  { id: 'social-reputation', name: 'Reputation Intelligence', color: '#F97316' },
  { id: 'growth-market', name: 'Market Performance', color: '#10B981' },
];

export const dashboardTiles: DashboardTile[] = [
  {
    id: 'payment-integrity',
    title: 'Payment Integrity',
    category: 'payment-integrity',
    isFeatured: true,
    usageCount: 42,
    lastAccessed: new Date('2025-01-16'),
    metrics: [
      { id: 'spend-per-claim', label: 'Spend per Claim', value: '$545', status: 'negative', trend: 'up' },
      { id: 'denial-rate', label: 'Denial Rate', value: '27.2%', status: 'positive', trend: 'down' },
      { id: 'overturn-rate', label: 'Overturn Rate', value: '18%', status: 'negative', trend: 'up' },
    ],
    insights: 'Digital-first providers handled the surge with –1.4 pts lower denials; non-digital cohorts drove +$1.8M spend.',
  },
  {
    id: 'claims-management',
    title: 'Claims Management',
    category: 'claims-management',
    isFeatured: true,
    usageCount: 38,
    lastAccessed: new Date('2025-01-15'),
    metrics: [
      { id: 'clean-claim', label: 'Clean Claim %', value: '72%', status: 'negative', trend: 'down' },
      { id: 'tat-median', label: 'TAT (median)', value: '10.4 days', status: 'negative', trend: 'up' },
      { id: 'rework-rate', label: 'Rework Rate', value: '12%', status: 'negative', trend: 'up' },
    ],
    insights: 'Rule-driven errors up 5%; TOPS config ticket issued. Potential $2.6M rework savings if corrected.',
  },
  {
    id: 'clinical-quality',
    title: 'Clinical Management',
    category: 'clinical-quality',
    isFeatured: true,
    usageCount: 35,
    lastAccessed: new Date('2025-01-14'),
    metrics: [
      { id: 'readmit-30day', label: 'Readmit 30-day', value: '13.6%', status: 'negative', trend: 'up' },
      { id: 'er-visits', label: 'ER Visits/1k', value: '587', status: 'negative', trend: 'up' },
      { id: 'gap-closure', label: 'Gap Closure', value: '78%', status: 'negative', trend: 'down' },
    ],
    insights: 'West region care team capacity breached 110% utilization; redistribute tele-nursing coverage.',
  },
  {
    id: 'finance-cost',
    title: 'Cost of Care',
    category: 'finance-cost',
    isFeatured: true,
    usageCount: 32,
    lastAccessed: new Date('2025-01-13'),
    metrics: [
      { id: 'paid-billed', label: 'Paid/Billed', value: '85.7%', status: 'positive', trend: 'up' },
      { id: 'allowed-billed', label: 'Allowed/Billed', value: '90.5%', status: 'neutral', trend: 'stable' },
      { id: 'pmpm', label: 'PMPM', value: '$601', status: 'negative', trend: 'up' },
    ],
    insights: 'Projected PMPM +0.6% next month if AQI persists; $18.6M avoidance via site-of-care shift 5% IP→OP.',
  },
  {
    id: 'healthcare-economics',
    title: 'Healthcare Economics',
    category: 'healthcare-economics',
    isFeatured: false,
    usageCount: 28,
    lastAccessed: new Date('2025-01-12'),
    metrics: [
      { id: 'ip-op-mix', label: 'IP/OP Mix', value: '62/38', status: 'negative', trend: 'up' },
      { id: 'cost-drivers', label: 'Cost Drivers', value: 'Oncology +$18', status: 'negative', trend: 'up' },
      { id: 'shiftable-spend', label: 'Shiftable Spend', value: '$22.5M/Q', status: 'positive', trend: 'stable' },
    ],
    insights: 'Air-quality-related spike cost ~$6.2M; temporary but forecasted for 3 weeks.',
  },
  {
    id: 'utilization-management',
    title: 'Utilization Management',
    category: 'utilization-management',
    isFeatured: false,
    usageCount: 25,
    lastAccessed: new Date('2025-01-11'),
    metrics: [
      { id: 'pa-tat', label: 'PA TAT', value: '22 hrs', status: 'positive', trend: 'down' },
      { id: 'pa-denial', label: 'PA Denial', value: '9.1%', status: 'negative', trend: 'up' },
      { id: 'pa-overturn', label: 'PA Overturn', value: '27%', status: 'negative', trend: 'up' },
    ],
    insights: 'PA Overturns up 3 pts; immediate rule synchronization needed in TOPS.',
  },
  {
    id: 'provider-experience',
    title: 'Provider Experience',
    category: 'provider-experience',
    isFeatured: false,
    usageCount: 22,
    lastAccessed: new Date('2025-01-10'),
    metrics: [
      { id: 'csat', label: 'CSAT', value: '4.1', status: 'negative', trend: 'down' },
      { id: 'inquiries', label: 'Inquiries', value: '740K', status: 'negative', trend: 'up' },
      { id: 'sentiment', label: 'Sentiment', value: '-0.12', status: 'negative', trend: 'down' },
    ],
    insights: 'CSAT drop correlates r = -0.58 with denial trend; mitigate by real-time provider notices.',
  },
  {
    id: 'member-experience',
    title: 'Member Experience',
    category: 'member-experience',
    isFeatured: false,
    usageCount: 20,
    lastAccessed: new Date('2025-01-09'),
    metrics: [
      { id: 'csat', label: 'CSAT', value: '4.3', status: 'negative', trend: 'down' },
      { id: 'inquiries', label: 'Inquiries', value: '1.2M', status: 'negative', trend: 'up' },
      { id: 'fcr', label: 'FCR', value: '78%', status: 'negative', trend: 'down' },
    ],
    insights: 'Billing calls ↑ 9%; publish FAQ before CMS rule takes effect.',
  },
  {
    id: 'digital-engagement',
    title: 'Digital Engagement',
    category: 'digital-engagement',
    isFeatured: false,
    usageCount: 18,
    lastAccessed: new Date('2025-01-08'),
    metrics: [
      { id: 'api-adoption', label: 'API Adoption', value: '45%', status: 'positive', trend: 'up' },
      { id: 'portal-sessions', label: 'Portal Sessions', value: '28M', status: 'positive', trend: 'up' },
      { id: 'manual-contact', label: 'Manual Contact', value: '5.3%', status: 'positive', trend: 'down' },
    ],
    insights: 'Outage impact contained via Cosmos fail-over; no claims delay > 6 hrs.',
  },
  {
    id: 'call-center-provider',
    title: 'Call Center - Provider',
    category: 'call-center-provider',
    isFeatured: false,
    usageCount: 16,
    lastAccessed: new Date('2025-01-07'),
    metrics: [
      { id: 'asa', label: 'ASA', value: '31 sec', status: 'positive', trend: 'stable' },
      { id: 'aht', label: 'AHT', value: '6 min 22 sec', status: 'negative', trend: 'up' },
      { id: 'contacts-per-1k', label: 'Contacts/1K Claims', value: '53', status: 'negative', trend: 'up' },
    ],
    insights: '2 FTE shortfall = +0.4 min AHT; hire immediate temps.',
  },
  {
    id: 'call-center-member',
    title: 'Call Center - Member',
    category: 'call-center-member',
    isFeatured: false,
    usageCount: 15,
    lastAccessed: new Date('2025-01-06'),
    metrics: [
      { id: 'asa', label: 'ASA', value: '28 sec', status: 'positive', trend: 'stable' },
      { id: 'aht', label: 'AHT', value: '5 min 41 sec', status: 'negative', trend: 'up' },
      { id: 'transfers', label: 'Transfers', value: '11%', status: 'negative', trend: 'up' },
    ],
    insights: 'Predictive staffing required for next 2 weeks.',
  },
  {
    id: 'network-contracting',
    title: 'Network & Contracting',
    category: 'network-contracting',
    isFeatured: false,
    usageCount: 14,
    lastAccessed: new Date('2025-01-05'),
    metrics: [
      { id: 'oon-spend', label: 'OON Spend', value: '4.8%', status: 'negative', trend: 'up' },
      { id: 'adequacy', label: 'Adequacy', value: '96%', status: 'negative', trend: 'down' },
      { id: 'coe-share', label: 'COE Share', value: '18%', status: 'neutral', trend: 'stable' },
    ],
    insights: 'OON spend +0.5 pt adds $3.2M; re-route claims to COE partners.',
  },
  {
    id: 'pharmacy',
    title: 'Pharmacy',
    category: 'pharmacy',
    isFeatured: false,
    usageCount: 13,
    lastAccessed: new Date('2025-01-04'),
    metrics: [
      { id: 'rx-pmpm', label: 'Rx PMPM', value: '$138', status: 'negative', trend: 'up' },
      { id: 'specialty-share', label: 'Specialty Share', value: '46%', status: 'negative', trend: 'up' },
      { id: 'adherence', label: 'Adherence (PDC≥80)', value: '82%', status: 'negative', trend: 'down' },
    ],
    insights: 'Non-fill spike cost ~$1.8M; activate co-pay assistance campaign.',
  },
  {
    id: 'risk-adjustment',
    title: 'Risk Adjustment',
    category: 'risk-adjustment',
    isFeatured: false,
    usageCount: 12,
    lastAccessed: new Date('2025-01-03'),
    metrics: [
      { id: 'raf', label: 'RAF', value: '0.94', status: 'negative', trend: 'down' },
      { id: 'unconfirmed-conditions', label: 'Unconfirmed Conditions', value: '18%', status: 'negative', trend: 'up' },
      { id: 'coding-accuracy', label: 'Coding Accuracy', value: '96.8%', status: 'positive', trend: 'stable' },
    ],
    insights: '2-week coding lag may drop RAF 0.02; targeted QA audits needed.',
  },
  {
    id: 'fraud-waste-abuse',
    title: 'Fraud, Waste, Abuse',
    category: 'fraud-waste-abuse',
    isFeatured: false,
    usageCount: 11,
    lastAccessed: new Date('2025-01-02'),
    metrics: [
      { id: 'recoveries-ytd', label: 'Recoveries YTD', value: '$72.4M', status: 'positive', trend: 'up' },
      { id: 'suspect-claims', label: 'Suspect Claims', value: '0.9%', status: 'positive', trend: 'down' },
      { id: 'pre-pay-hit-rate', label: 'Pre-Pay Hit Rate', value: '68%', status: 'positive', trend: 'up' },
    ],
    insights: 'Tighten lab rules to cut noise by 0.3 pt without missed fraud.',
  },
  {
    id: 'compliance-regulatory',
    title: 'Compliance & Regulatory',
    category: 'compliance-regulatory',
    isFeatured: false,
    usageCount: 10,
    lastAccessed: new Date('2025-01-01'),
    metrics: [
      { id: 'sla-met', label: 'SLA Met', value: '99.1%', status: 'positive', trend: 'up' },
      { id: 'filing-exceptions', label: 'Filing Exceptions', value: '0.3%', status: 'positive', trend: 'down' },
      { id: 'phi-incidents', label: 'PHI Incidents', value: '0', status: 'positive', trend: 'stable' },
    ],
    insights: 'PA rule implementation on track; testing window ends in 4 days.',
  },
  {
    id: 'data-quality',
    title: 'Data Quality & Platform',
    category: 'data-quality',
    isFeatured: false,
    usageCount: 9,
    lastAccessed: new Date('2024-12-31'),
    metrics: [
      { id: 'data-defects', label: 'Data Defects', value: '0.7%', status: 'negative', trend: 'up' },
      { id: 'uptime', label: 'Uptime', value: '99.92%', status: 'positive', trend: 'up' },
      { id: 'latency', label: 'Latency', value: '410 ms', status: 'negative', trend: 'up' },
    ],
    insights: 'No claim loss; data integrity validated post-incident.',
  },
  {
    id: 'hr-workforce',
    title: 'HR/Workforce',
    category: 'hr-workforce',
    isFeatured: false,
    usageCount: 8,
    lastAccessed: new Date('2024-12-30'),
    metrics: [
      { id: 'time-to-hire', label: 'Time-to-Hire', value: '28 days', status: 'negative', trend: 'up' },
      { id: 'turnover', label: 'Turnover', value: '17%', status: 'negative', trend: 'up' },
      { id: 'training-compliance', label: 'Training Compliance', value: '86%', status: 'negative', trend: 'down' },
    ],
    insights: 'Temp hires for Claims Ops approved; time-to-hire goal 24 days.',
  },
  {
    id: 'social-reputation',
    title: 'Reputation Intelligence',
    category: 'social-reputation',
    isFeatured: false,
    usageCount: 7,
    lastAccessed: new Date('2024-12-29'),
    metrics: [
      { id: 'sentiment-index', label: 'Sentiment Index', value: '+0.18', status: 'negative', trend: 'down' },
      { id: 'mentions', label: 'Mentions', value: '+22%', status: 'negative', trend: 'up' },
      { id: 'issue-index', label: 'Issue Index', value: '0.34', status: 'negative', trend: 'up' },
    ],
    insights: 'Sentiment ↓ post-rule release; publish clarifying statement w/in 48 hrs.',
  },
  {
    id: 'growth-market',
    title: 'Market Performance',
    category: 'growth-market',
    isFeatured: false,
    usageCount: 6,
    lastAccessed: new Date('2024-12-28'),
    metrics: [
      { id: 'net-adds', label: 'Net Adds', value: '+38K', status: 'positive', trend: 'up' },
      { id: 'broker-nps', label: 'Broker NPS', value: '46', status: 'negative', trend: 'down' },
      { id: 'cac-per-member', label: 'CAC $/Member', value: '$112', status: 'negative', trend: 'up' },
    ],
    insights: 'Pipeline delay forecast Q1; activate broker enablement campaign.',
  },
];
